# Generated by Django 5.2.7 on 2025-10-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_profile_timezone"),
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("happy", "😊 Happy"),
                            ("normal", "😐 Normal"),
                            ("sad", "😞 Sad"),
                            ("stressed", "😰 Stressed"),
                            ("excited", "🤩 Excited"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotion_entries",
                        to="accounts.profile",
                    ),
                ),
                (
                    "study_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotion_entry",
                        to="study.studysession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emotion Entry (Cảm xúc)",
                "verbose_name_plural": "Emotion Entries (Các cảm xúc)",
                "ordering": ["-created_at"],
            },
        ),
    ]
