# Generated by Django 5.2.7 on 2025-11-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotion", "0001_initial"),
        ("study", "0002_rename_points_awards_studysession_points_awarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emotionentry",
            name="emotion",
            field=models.CharField(
                choices=[
                    ("happy", "😊 Happy"),
                    ("sad", "😢 Sad"),
                    ("tired", "😴 Tired"),
                    ("calm", "😌 Calm"),
                    ("stressed", "😤 Stressed"),
                    ("excited", "🤩 Excited"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="emotionentry",
            name="study_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emotion",
                to="study.studysession",
            ),
        ),
    ]
