# Generated by Django 5.2.7 on 2025-11-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musictrack",
            name="playlist",
        ),
        migrations.RemoveField(
            model_name="usermusicsession",
            name="playlist",
        ),
        migrations.RemoveField(
            model_name="usermusicsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userspotifyprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="musictrack",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="musictrack",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="musictrack",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="musictrack",
            name="spotify_cover_url",
        ),
        migrations.RemoveField(
            model_name="musictrack",
            name="spotify_preview_url",
        ),
        migrations.RemoveField(
            model_name="musictrack",
            name="spotify_track_id",
        ),
        migrations.RemoveField(
            model_name="musictrack",
            name="track_order",
        ),
        migrations.AddField(
            model_name="musictrack",
            name="category",
            field=models.CharField(
                choices=[
                    ("lofi", "Lo-Fi Beats"),
                    ("nature", "Nature Sounds"),
                    ("classical", "Classical"),
                    ("ambient", "Ambient"),
                    ("other", "Other"),
                ],
                default="lofi",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="musictrack",
            name="cover_color",
            field=models.CharField(
                default="#6C63FF", help_text="Mã màu hex, ví dụ #6C63FF", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="musictrack",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="music/covers/"),
        ),
        migrations.AddField(
            model_name="musictrack",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="musictrack",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="musictrack",
            name="audio_file",
            field=models.FileField(upload_to="music/tracks/"),
        ),
        migrations.DeleteModel(
            name="FavoritePlaylist",
        ),
        migrations.DeleteModel(
            name="MusicPlaylist",
        ),
        migrations.DeleteModel(
            name="UserMusicSession",
        ),
        migrations.DeleteModel(
            name="UserSpotifyProfile",
        ),
    ]
