# Generated by Django 5.2.8 on 2025-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_remove_musictrack_playlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musictrack",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Track mặc định cho mọi user"
            ),
        ),
        migrations.AddField(
            model_name="musictrack",
            name="static_audio_path",
            field=models.CharField(
                blank=True,
                help_text="Đường dẫn tới file audio trong static folder, ví dụ: music/default/track.mp3",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="musictrack",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="music/tracks/"),
        ),
    ]
