# Generated by Django 5.2.7 on 2025-11-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studysession",
            old_name="points_awards",
            new_name="points_awarded",
        ),
    ]
