# Generated by Django 5.2.8 on 2025-11-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_rename_points_awards_studysession_points_awarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
