# Generated by Django 5.2.8 on 2025-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_subject_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='actual_study_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
