# Generated by Django 5.2.8 on 2025-11-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_studysession_actual_study_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studysession",
            name="actual_study_seconds",
        ),
    ]
