# Generated by Django 5.2.8 on 2025-11-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_remove_studysession_actual_study_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="total_pause_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
