# Generated by Django 5.2.7 on 2025-11-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="actual_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("study", "📚 Study"),
                    ("homework", "📝 Homework"),
                    ("project", "💼 Project"),
                    ("review", "📖 Review"),
                    ("other", "📌 Other"),
                ],
                default="study",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="predicted_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "🔵 Low"),
                    ("medium", "🟡 Medium"),
                    ("high", "🔴 High"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
