# Generated by Django 5.2.7 on 2025-10-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="email_reminders",
            new_name="email_reminder",
        ),
    ]
