# Generated by Django 5.2.7 on 2025-10-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_email_reminders_profile_email_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=models.CharField(default="UTC + 7 hours", max_length=50),
        ),
    ]
