# Generated by Django 5.2.7 on 2025-10-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_profile_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualizationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart (Biểu đồ cột)"),
                            ("line", "Line Chart (Biểu đồ đường)"),
                            ("pie", "Pie Chart (Biểu đồ tròn)"),
                        ],
                        default="bar",
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualization_config",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualization Config (Cấu hình biểu đồ)",
                "verbose_name_plural": "Visualization Configs (Cấu hình biểu đồ)",
                "ordering": ["-updated_at"],
            },
        ),
    ]
