# Generated by Django 5.2.8 on 2025-11-22 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studysession",
            name="duration",
        ),
        migrations.AddField(
            model_name="studysession",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viz_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viz_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
