# Generated by Django 5.2.7 on 2025-10-21 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_profile_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=100)),
                (
                    "image_idle",
                    models.ImageField(
                        blank=True, null=True, upload_to="characters/idle/"
                    ),
                ),
                (
                    "image_talk",
                    models.ImageField(
                        blank=True, null=True, upload_to="characters/talk/"
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Thường"),
                            ("rare", "Hiếm"),
                            ("epic", "Cực hiếm"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("motivation_quotes", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Character (Nhân vật)",
                "verbose_name_plural": "Characters (Danh sách nhân vật)",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("reward_coins", models.PositiveIntegerField(default=0)),
                ("earned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_claimed", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement (Thành tích)",
                "verbose_name_plural": "Achievements (Các thành tích)",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_by_users",
                        to="gamification.character",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory (Kho nhân vật)",
                "verbose_name_plural": "Inventories (Kho nhân vật của người dùng)",
                "unique_together": {("profile", "character")},
            },
        ),
    ]
